### ISSUE TITLE
Bug in VideoProcessingSettings.Seek

### ISSUE THREAD

**Issue by x27** [askatmaster/MediaFileProcessor#2]
Method is:

    public VideoProcessingSettings Seek(TimeSpan seek)
    {
        _stringBuilder.Append($" -ss {seek.TotalSeconds:00:00:00.000} ".Replace(",", "."));
        return this;
    }

Make test code:

	public static void Main()
	{
		var ts = new TimeSpan(0,0,3,1,5);
		Console.WriteLine($"{ts.TotalSeconds:00:00:00.000}");
	}

Result:
00:01:81.005
it's not valid value for -ss key of ffmpeg

**Comment by askatmaster** [comment]
Okay, I'll fix it. Thank you)
